Add acceleration-based SNS IK base solver with unit test
RethinkRobotics-opensource/sns_ik pull request #93
Opened 2018-06-25 13:32 UTC by robodreamer

This commit adds acceleration-based sns ik base solver including
unit tests. It was written on top of Matt's initial code ported from 
base velocity sns ik solver.

2018-06-25 15:42 UTC, MatthewPeterKelly requested changes
Looks great!  I made a few suggestions, mostly related to documentation and reducing code duplication.

2018-06-25 15:42 UTC, MatthewPeterKelly commented on sns_ik_lib/include/sns_ik/sns_acc_ik_base.hpp
> +  enum class ExitCode {
This duplicated the same enum that is present in the velocity solver. That is fine for now, but ultimately there should be a single base class for both solvers that removes this and other code duplication.

2018-06-25 15:42 UTC, MatthewPeterKelly commented on sns_ik_lib/src/sns_acc_ik_base.cpp
> + * @author Matthew Kelly
Add @author Andy Park to the next line

2018-06-25 15:42 UTC, MatthewPeterKelly commented on sns_ik_lib/include/sns_ik/sns_acc_ik_base.hpp
> + * @author Matthew Kelly
Add @author Andy Park to the next line

2018-06-25 15:42 UTC, MatthewPeterKelly commented on sns_ik_lib/src/sns_acc_ik_base.cpp
> +    ROS_ERROR("Bad Input: dx.size() > 0 is required!");
dx  -->  ddx

2018-06-25 15:42 UTC, MatthewPeterKelly commented on sns_ik_lib/test/sns_acc_ik_base_test.cpp
> + *    Copyright 2018 Rethink Robotics
Add @author Andy Park

2018-06-25 15:42 UTC, MatthewPeterKelly commented on sns_ik_lib/test/sns_acc_ik_base_test.cpp
> +void checkEqualVector(const Eigen::VectorXd& A, const Eigen::VectorXd& B, double tol)
This function and the next one duplicate an existing utility function in the velocity test. These should both be moved to some test utilities header that can be accessed by any test. I suggest making a new file called "test_utilities" that lives next to "rng_utilities".

2018-06-25 15:42 UTC, MatthewPeterKelly commented on sns_ik_lib/test/sns_acc_ik_base_test.cpp
> + * This test is for the solveAccIkBasic()
Can you add some more description here?  I think the function name in the existing documentation might also be wrong.

2018-06-25 15:42 UTC, MatthewPeterKelly commented on sns_ik_lib/test/sns_acc_ik_base_test.cpp
> + * This test is for the solveAccIkBasic()
More information in the documentation about the test please.

2018-06-25 15:49 UTC, robodreamer commented on sns_ik_lib/include/sns_ik/sns_acc_ik_base.hpp
> +  enum class ExitCode {
I see. I will note that when I merge them into a single base class.

2018-06-25 17:24 UTC, robodreamer commented on sns_ik_lib/test/sns_acc_ik_base_test.cpp
> +void checkEqualVector(const Eigen::VectorXd& A, const Eigen::VectorXd& B, double tol)
Good suggestion!

2018-06-25 20:18 UTC, MatthewPeterKelly approved these changes
Excellent - ship it!

2018-06-28 11:13 UTC, robodreamer commented
@IanTheEngineer, hey Ian if you are okay, I will go ahead and merge this pull request.

2018-06-28 16:19 UTC, IanTheEngineer approved these changes
This looks great, Andy! Huge improvement in additional functionality. Thanks!

2018-06-28 19:20 UTC, merged